apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: BETA
  name: "debugging-foo-sidecar"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
        - image: FOO-IMAGE
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
        - image: SIDECAR-IMAGE
          env:
            - name: PORT
              value: "5000"
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
