apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: BETA
  name: "debugging-foo-sidecar"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
        - name: foo
          image: FOO-IMAGE
          startupProbe:
            httpGet:
              path: /
          ports:
            - containerPort: 8080
        - name: sidecar
          image: SIDECAR-IMAGE
          startupProbe:
            httpGet:
              path: /
          env:
            - name: PORT
              value: "5000"
